name: Lenas AI Profiler Python

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
      issues: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
        sudo apt-get install haveged
        sudo systemctl start haveged
        pip install .[tensorflow]
        pip install .[torch]

    - name: Run tests
      run: |
        python -m unittest discover -s tests
    
    - name: Build Docs
      run: |
        sphinx-apidoc -o docs/source/ .
        cd docs
        make html
    
    - name: Create .nojekyll file
      run: echo '' > docs/build/html/.nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
        force_orphan: true





















    

















